### PR TITLE
LF line endings and trimming trailing spaces

### PR DESCRIPTION
**Pull request by szepeviktor**
393 files changed !!!

### CODE REVIEW

**Comment by sendtogeo** [comment]
Do you know the issues if we couldn't add lines like this?

**Comment by szepeviktor** [comment]
I am very, I do not understand your question.

**Comment by szepeviktor** [comment]
You can check this PR this way:
https://github.com/seopanel/Seo-Panel/pull/2/files?w=1
GitHub will hide whitespace changes https://github.com/tiimgreen/github-cheat-sheet#ignore-whitespace

**Comment by szepeviktor** [comment]
This is a code styling issue..

**Comment by szepeviktor** [comment]
It is about uniform line ends.

**Comment by szepeviktor** [comment]
You can achieve this by these command (on Linux or Mac or Windows/Cygwin of GitBash)
```bash
find -not -path '*/.*' -type f '(' -path "*.php" -o -path "*.js" -o -path "*.css" ')' -exec dos2unix '{}' ';'
find -not -path '*/.*' -type f '(' -path "*.php" -o -path "*.js" -o -path "*.css" ')' -exec sed -i 's/[ \t]*$//' '{}' ';'
```

**Comment by szepeviktor** [comment]
Further reading: https://help.github.com/articles/dealing-with-line-endings/

**Comment by szepeviktor** [comment]
Could you format your code?

- LF lineends
- only tabs or only spaces

If you install [Git bash](https://git-scm.com/downloads) or have Cygwin installed you could use these tools: https://github.com/seopanel/Seo-Panel/pull/2#issuecomment-109638621

**Comment by szepeviktor** [comment]
@sendtogeo Please consider setting your name and email in your git config. Commits by `root`:
https://github.com/seopanel/Seo-Panel/commits/develop

**Comment by sendtogeo** [comment]
@szepeviktor  Thanks, Added name to the commits like your suggestion.

https://github.com/seopanel/Seo-Panel/commits/develop

**Comment by szepeviktor** [comment]
Please consider normalizing indents, line ends and striping trailing spaces.
Then keep your code clean.

**Pull request closed without merging**
