### PR TITLE
Short opentags

### PR DESCRIPTION
**Pull request by szepeviktor**
There are many more.
Please search for this regexp:
```
<\?[^p]
```
It gives some false positives.

### CODE REVIEW

**Comment by szepeviktor** [comment]
I was looking in **Google Code's SVN**, in the `seopanel.v.3.7.0.beta` branch where you check in your commits.

**Comment by sendtogeo** [comment]
Viktor,

Sure I will add it.

currently commiting to that branch. But soon wil be moved to github before
aug 25.



Regards,
Geo Varghese
www.seofreetools.net

**Comment by szepeviktor** [comment]
Good morning!

Do you have time to remove short open tags?

**Comment by szepeviktor** [comment]
Please consider removing all short open-tags.

**Comment by sendtogeo** [comment]
Sure, I have already started using github this week. Just created a develop
branch and I am adding changes to it now.

https://github.com/seopanel/Seo-Panel/branches



Regards,
Geo Varghese
www.seofreetools.net

**Comment by sendtogeo** [comment]
Can you send me pull request to this branch?



Regards,
Geo Varghese
www.seofreetools.net

**Comment by szepeviktor** [comment]
The thing is there are much more short open-tags than the above 3.
Sorry, I don't have time to go through all of your code.
Search for in every file:
```
<\?[^p]
```

**Comment by szepeviktor** [comment]
Do you plan to remove short open tags?

**Comment by szepeviktor** [comment]
@sendtogeo Develop branch contains:

```
themes/simple/views/theme/listthemes.ctp.php:<? echo $listInfo['installed'] ?
themes/simple/views/backlink/findbacklink.ctp.php:<? echo urlencode($url); ?><?php
themes/simple/views/backlink/findbacklink.ctp.php:<? echo urlencode($url); ?><?php
themes/simple/views/backlink/findbacklink.ctp.php:<? echo urlencode($url); ?><?php
themes/simple/views/directory/showsubmissionstats.ctp.php:<? if(!empty($msg)){
themes/simple/views/directory/showsubmissionstats.ctp.php:<?
themes/simple/views/directory/showsubmissionform.ctp.php:<? if(!empty($msg)){
themes/simple/views/directory/showsubmissionform.ctp.php:<?
themes/simple/views/directory/showsubmissionform.ctp.php:<? if (!empty($reciprocalDir)) {
themes/simple/views/directory/showsubmissionform.ctp.php:<? } ?>
themes/simple/views/directory/showsubmissionform.ctp.php:<? if(!empty($captchaUrl)){ ?>
themes/simple/views/directory/showsubmissionform.ctp.php:<? } ?>
themes/simple/views/usertypes/new.ctp.php:<? if(!empty($msg)){
themes/simple/views/usertypes/new.ctp.php:<?
themes/simple/views/saturationchecker/findsearchenginesaturation.ctp.php:<? echo urlencode($url); ?><?php
themes/simple/views/saturationchecker/findsearchenginesaturation.ctp.php:<? echo urlencode($url); ?><?php
themes/simple/views/keyword/list.ctp.php:<? echo empty($listInfo['country_
themes/simple/views/keyword/list.ctp.php:<? echo empty($listInfo['lang_nam
themes/simple/views/keyword/list.ctp.php:<?if($listInfo['webstatus'] && $l
themes/simple/views/user/editmyprofile.ctp.php:<? if(!empty($msg)){ showSuccessM
themes/simple/views/seoplugins/listseoplugins.ctp.php:<? echo $listInfo['installed'] ?
themes/simple/views/report/report.ctp.php:<? echo stripslashes($listInfo['t
themes/simple/views/report/report.ctp.php:<? echo stripslashes($listInfo['d
themes/simple/views/report/report.ctp.php:<?
themes/simple/views/report/archive.ctp.php:<?
themes/simple/views/report/showquickrankchecker.ctp.php:<? echo stripslashes($listInfo['t
themes/simple/views/report/showquickrankchecker.ctp.php:<? echo stripslashes($listInfo['d
themes/simple/views/report/showquickrankchecker.ctp.php:<?
themes/simple/views/report/reportsummary.ctp.php:<?
themes/simple/views/report/timereport.ctp.php:<? echo stripslashes($listInfo['t
themes/simple/views/report/timereport.ctp.php:<? echo stripslashes($listInfo['d
themes/simple/views/report/timereport.ctp.php:<?
themes/simple/views/rank/findquickrank.ctp.php:<? echo urlencode($url); ?><?php
themes/simple/views/rank/findquickrank.ctp.php:<? echo urlencode($url); ?><?php
themes/simple/views/rank/rankreport.ctp.php:<?
themes/simple/views/seotools/listseotools.ctp.php:<?echo $listInfo['id'];?></td>
themes/simple/views/seotools/listseotools.ctp.php:<? echo $listInfo['name'];?></td>
themes/simple/views/seotools/listseotools.ctp.php:<? echo $accessLink;?></td>
themes/simple/views/seotools/listseotools.ctp.php:<? echo $reportgenLink;?></td>
themes/simple/views/seotools/listseotools.ctp.php:<? echo $cronLink;?></td>
themes/simple/views/seotools/listseotools.ctp.php:<? echo $activateLink;?></td>
themes/simple/views/website/new.ctp.php:<? if(!empty($msg)){
themes/simple/views/website/new.ctp.php:<?
themes/classic/views/theme/listthemes.ctp.php:<? echo $listInfo['installed'] ?
themes/classic/views/backlink/findbacklink.ctp.php:<? echo urlencode($url); ?><?php
themes/classic/views/backlink/findbacklink.ctp.php:<? echo urlencode($url); ?><?php
themes/classic/views/backlink/findbacklink.ctp.php:<? echo urlencode($url); ?><?php
themes/classic/views/directory/showsubmissionstats.ctp.php:<? if(!empty($msg)){
themes/classic/views/directory/showsubmissionstats.ctp.php:<?
themes/classic/views/directory/showsubmissionform.ctp.php:<? if(!empty($msg)){
themes/classic/views/directory/showsubmissionform.ctp.php:<?
themes/classic/views/directory/showsubmissionform.ctp.php:<? if (!empty($reciprocalDir)) {
themes/classic/views/directory/showsubmissionform.ctp.php:<? } ?>
themes/classic/views/directory/showsubmissionform.ctp.php:<? if(!empty($captchaUrl)){ ?>
themes/classic/views/directory/showsubmissionform.ctp.php:<? } ?>
themes/classic/views/usertypes/new.ctp.php:<? if(!empty($msg)){
themes/classic/views/usertypes/new.ctp.php:<?
themes/classic/views/saturationchecker/findsearchenginesaturation.ctp.php:<? echo urlencode($url); ?><?php
themes/classic/views/saturationchecker/findsearchenginesaturation.ctp.php:<? echo urlencode($url); ?><?php
themes/classic/views/keyword/list.ctp.php:<? echo empty($listInfo['country_
themes/classic/views/keyword/list.ctp.php:<? echo empty($listInfo['lang_nam
themes/classic/views/keyword/list.ctp.php:<?if($listInfo['webstatus'] && $l
themes/classic/views/user/editmyprofile.ctp.php:<? if(!empty($msg)){ showSuccessM
themes/classic/views/seoplugins/listseoplugins.ctp.php:<? echo $listInfo['installed'] ?
themes/classic/views/report/report.ctp.php:<? echo stripslashes($listInfo['t
themes/classic/views/report/report.ctp.php:<? echo stripslashes($listInfo['d
themes/classic/views/report/report.ctp.php:<?
themes/classic/views/report/archive.ctp.php:<?
themes/classic/views/report/showquickrankchecker.ctp.php:<? echo stripslashes($listInfo['t
themes/classic/views/report/showquickrankchecker.ctp.php:<? echo stripslashes($listInfo['d
themes/classic/views/report/showquickrankchecker.ctp.php:<?
themes/classic/views/report/reportsummary.ctp.php:<?
themes/classic/views/report/timereport.ctp.php:<? echo stripslashes($listInfo['t
themes/classic/views/report/timereport.ctp.php:<? echo stripslashes($listInfo['d
themes/classic/views/report/timereport.ctp.php:<?
themes/classic/views/rank/findquickrank.ctp.php:<? echo urlencode($url); ?><?php
themes/classic/views/rank/findquickrank.ctp.php:<? echo urlencode($url); ?><?php
themes/classic/views/rank/rankreport.ctp.php:<?
themes/classic/views/seotools/listseotools.ctp.php:<?echo $listInfo['id'];?></td>
themes/classic/views/seotools/listseotools.ctp.php:<? echo $listInfo['name'];?></td>
themes/classic/views/seotools/listseotools.ctp.php:<? echo $accessLink;?></td>
themes/classic/views/seotools/listseotools.ctp.php:<? echo $reportgenLink;?></td>
themes/classic/views/seotools/listseotools.ctp.php:<? echo $cronLink;?></td>
themes/classic/views/seotools/listseotools.ctp.php:<? echo $activateLink;?></td>
themes/classic/views/website/importwebsites.ctp.php:<?
themes/classic/views/website/importwebsites.ctp.php:<?=$spTextWeb['Website CSV File']
themes/classic/views/website/new.ctp.php:<? if(!empty($msg)){
themes/classic/views/website/new.ctp.php:<?
```

Please fix them. Thank you.

**Comment by sendtogeo** [comment]
sure i will execute the script to fix it. Thanks for the update.

I am planning to use github for all from now to track the release and other related changes

**Comment by szepeviktor** [comment]
An idea: fix them as you can then disable PHP directive `short_open_tag` and try to use SeoPanel and see...

**Comment by szepeviktor** [comment]
Maybe: http://stackoverflow.com/questions/684587/batch-script-to-replace-php-short-open-tags-with-php/1647429#1647429

**Pull request closed without merging**
