### PR TITLE
Removed empty config file

### PR DESCRIPTION
**Pull request by szepeviktor**
`config/sp-config.php`

### CODE REVIEW

**Comment by szepeviktor** [comment]
I could overwrite your real config.

**Comment by sendtogeo** [comment]
Installation will fail if no config file is existing otherwise user have to create  new file.

**Comment by szepeviktor** [comment]
OK. I close this.
Please think about updating. It should be possible through git.

**Comment by szepeviktor** [comment]
(I keep my SeoPanel installation under git control.)

**Pull request closed without merging**
